# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSmokeTest():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminPage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
    self.driver.set_window_size(1436, 887)
    self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(2)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".myinput:nth-child(2)")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > div").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["root"])
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
  
  def test_directoryPage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
    self.driver.set_window_size(1436, 887)
    self.driver.find_element(By.ID, "directory-grid").click()
    self.driver.find_element(By.ID, "directory-list").click()
    self.driver.find_element(By.ID, "directory-grid").click()
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.ID, "directory-list").click()
    elements = self.driver.find_elements(By.ID, "directory-list")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "directory-grid").click()
    self.driver.find_element(By.ID, "directory-selector").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
    self.driver.find_element(By.ID, "directory-data").click()
    self.driver.find_element(By.ID, "directory-list").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
    self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").click()
  
  def test_homePage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 > h4")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 > h4").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 > h4")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
  
  def test_joinPage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
    self.driver.set_window_size(1436, 887)
    self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(2)").text == "First Name"
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("Peter")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("Pumpkin")
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("ATM")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").send_keys("Dr")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("peter@gmail.com")
    self.driver.find_element(By.NAME, "cellphone").click()
    self.driver.find_element(By.NAME, "cellphone").send_keys("111-222-3456")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".myradio:nth-child(15)").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("localhost.com")
    self.driver.find_element(By.CSS_SELECTOR, "textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, "textarea").send_keys("Business Desc")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("www.business.com")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("https://www.business.com")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > .left-justify").text == "peter@gmail.com"
  
